---
- name: Install Homebrew (macOS)
  block:
    - name: Install Homebrew
      shell: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      args:
        creates: /usr/local/bin/brew
      when: ansible_os_family == "Darwin"

    - name: Add Homebrew to PATH (macOS)
      lineinfile:
        path: "{{ user_home }}/.zshrc"
        line: 'eval "$(/opt/homebrew/bin/brew shellenv)"'
        state: present
      when: ansible_os_family == "Darwin" 