---
- name: Setup Developer Environment
  hosts: localhost
  become: yes
  gather_facts: yes

  pre_tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
      when: ansible_os_family == "Debian"

    - name: Install required packages
      package:
        name: "{{ item }}"
        state: present
      loop:
        - python3-pip
        - python3-venv
        - git
        - curl
        - wget
        - gnupg
        - software-properties-common
        - apt-transport-https
        - ca-certificates
      when: ansible_os_family == "Debian"

  roles:
    - role: package_manager
    - role: development_tools
    - role: databases
    - role: message_brokers
    - role: system_tools
    - role: ides_editors
    - role: browsers
    - role: communication_tools
    - role: development_apps

- name: Install development environment
  hosts: all
  become: yes
  tasks:
    - name: Include OS-specific tasks
      include_tasks: "roles/{{ ansible_os_family | lower }}/tasks/main.yml"
      when: ansible_os_family in ['Darwin', 'Debian']
      ignore_errors: yes

    - name: Include Raspberry Pi specific tasks
      include_tasks: roles/raspberry/tasks/main.yml
      when: ansible_os_family == 'Debian' and ansible_architecture == 'aarch64'

    - name: Include Ubuntu specific tasks
      include_tasks: roles/ubuntu/tasks/main.yml
      when: ansible_os_family == 'Debian' and ansible_distribution == 'Ubuntu' 